# CMake - Testing using Catch2
Catch2 is mainly a unit testing framework for C++, but it also provides basic micro-benchmarking features, and simple BDD macro.

:toc:
:sectnums:

== Introduction
Catch2's main advantag eis that using it is both simple and natural. Test names do not have to be valid identifiers, assertion looks like normal C++ boolean exoressions, and section provide a nice and local way to share set-up and tear-down code in tests.

=== Example unittest
The following example is about unit test using the Catch2 framework.
```cpp
#include <catch2/catch_test_macros.hpp>
#include <cstdint>

uint32_t factorial( uint32_t number ) {
    return number <= 1 ? number : factorial(number-1) * number;
}

TEST_CASE( "Factorials are computed", "[factorial]" ) {
    REQUIRE( factorial( 1) == 1 );
    REQUIRE( factorial( 2) == 2 );
    REQUIRE( factorial( 3) == 6 );
    REQUIRE( factorial(10) == 3'628'800 );
}
```

=== Example microbenchmark
The following example is about using Catc2 to make some micro benchmark
```cpp
#include <catch2/catch_test_macros.hpp>
#include <catch2/benchmark/catch_benchmark.hpp>

#include <cstdint>

uint64_t fibonacci(uint64_t number) {
    return number < 2 ? number : fibonacci(number - 1) + fibonacci(number - 2);
}

TEST_CASE("Benchmark Fibonacci", "[!benchmark]") {
    REQUIRE(fibonacci(5) == 5);

    REQUIRE(fibonacci(20) == 6'765);
    BENCHMARK("fibonacci 20") {
        return fibonacci(20);
    };

    REQUIRE(fibonacci(25) == 75'025);
    BENCHMARK("fibonacci 25") {
        return fibonacci(25);
    };
}
```

NOTE: Benchmarks are not run by default, so you need to run it explicitly with the [!benchmark] tag.

== Integration
In order to use `Catch2` for our project, we need to fetch it and use it in our build system, and there is a possibility for you to make use of CMake to build and compile the Catch2 library

=== Catch2 using CMake
Because Catch2 is used through CMake, it also provides a couple of integration points for the users such as:

* Catch2 exports a (namespace) CMake target
* Catch2 repository contains CMake scripts for automatic registration of `TEST_CASE` in CTest.

==== CMake targets
Catch2's CMake build exports two targets, `Catch2::Catch2`, and `Catch2::Catch2WithMain`. If you do not need custom `main` function, you should be using the latter (and only the latter). Linking against it will add the proper include paths and link your target together with 2 static libraries that implement Catch2 and its main respectively.

If you need custom `main` instead, you should link only against `Catc2::Catch2`.

That means that if `Catch2` has been installed on the system, it should be enough to do so:

===== Catch2 using find_package

```cmake
find_package(Catch2 3 REQUIRED)
# These tests can use the Catch2-provided main
add_executable(tests test.cpp)
target_link_libraries(tests PRIVATE Catch2::Catch2WithMain)

# These tests need their own main
add_executable(custom-main-test test.cpp test-main.cpp)
target_link_libraries(custom-main-test PRIVATE Catch2::Catch2)
```

These targets are also provided when Catch2 is used as a subdirectory. Assuming Catch2 has been cloned to `lib/Catch2`, you only need to replace the `find_package` call with `add_subdirectory(lib/Catch2)` and the snippet above will works.

===== Catch2 using FetchContent

Another possibility to fetch the Catch2 library is by using `FetchContent` module onto the CMake:

```cmake
include(FetchContent)
FetchContent_Declare(
    Catch2
    GIT_REPOSITORY  https://github.com/catchorg/catch2.git
    GIT_TAG         v3.8.1
)

FetchContent_MakeAvailable(Catch2)

add_executable(tests test.cpp)
target_link_libraries(tests PRIVATE Catch2::Catch2WithMain)
```

IMPORTANT: If you are making use of a testing library in your project, you should be aware that you will need in your main `CMakeLists.txt` file to add the `enable_testing()` command before adding the tests.